---
title: "WithKickMods"
output: html_document
date: "2023-11-25"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(faraway)
library(MASS)
library(readr)
library(rvest)
library(curl)
library(dplyr)
library(forcats)
library(lme4)
library(pbkrtest)
library(RLRsim)
library(pscl)
library(Matrix)
library(mgcv)
```

CLEAN
```{r}
bg = read_csv("/Users/coramcanulty/Desktop/STOR 320/GamesWithKICK.csv")
bg
bg$yeargroup = cut(bg$yearpublished,
    breaks = c(1970, 1980, 1990, 2000, 2010, 2020),
    include.lowest = T,
    right = F)
bg$yeargroup = as_factor(bg$yeargroup)
levels(bg$yeargroup) = c("1970s", "1980s","1990s","2000s","2010s")

bg$weightgroup = cut(bg$avgweight,
    breaks = c(0,1, 2, 3, 4,5),
    include.lowest = T,
    right = F)
levels(bg$weightgroup) = c("0-1","1-2","2-3","3-4","4-5")

bg$ComMinBin = cut(as.numeric(bg$min_community),
    breaks = c(0,1,2,3,4,5,6,7,8,9,10,50),
    include.lowest = T,
    right = T)
levels(bg$ComMinBin)= c("0-1","1-2","2-3","3-4","4-5","5-6", "6-7", "7-8","8-9","9-10","10+")

bg$ComPlayerGroup = cut(as.numeric(bg$min_community),
    breaks = c(0,1,30),
    include.lowest = T,
    right = T)
levels(bg$ComPlayerGroup) = c("SoloOption","Multi")

bg$kick = factor(bg$kick)

bg3 = bg %>%
  mutate(totalmedia = weblink+blogs+podcast+news)

bg4 = bg3 %>%
  filter(baverage>0, totalmedia>0, numplays>0) %>%
  mutate(logtotalmedia = log(totalmedia), lognumplays = log(numplays))
bg5 = bg4 %>%
  filter(yearpublished>1900)

#code for numerical playerage only
player_bg_data <- bg %>%
  mutate(log_plays=log(numplays+1), totalmedia = news+blogs+podcast+weblink, logtotalmedia = log(totalmedia +1)) %>%
  filter(baverage != 0) %>%
  filter(grepl("^\\d+$", playerage)) %>%
  filter(playerage != '(no votes)') %>%
  group_by(playerage) %>%
  add_count(log_plays) 

bg4<- bg %>%
  mutate(log_plays=log(numplays+1), totalmedia = news+blogs+podcast+weblink, logtotalmedia = log(totalmedia +1)) %>%
  filter(baverage != 0) %>%
  filter(grepl("^\\d+$", playerage)) %>%
  filter(playerage != '(no votes)') %>%
  group_by(playerage) %>%
  add_count(log_plays)
```

GRAPHS
```{r}
bg %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = avgweight, y = baverage, color = kick), alpha = .2) +
  geom_smooth(aes(x = avgweight, y = baverage, color = kick))

bg3 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = log(totalmedia), y = baverage, color = kick), alpha = .2) +
  geom_smooth(aes(x = log(totalmedia), y = baverage, color = kick))

bg3 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = log(totalmedia), y = baverage, color = kick))

bg3 %>%
  group_by(kick) %>%
  summarise(AvMedia = mean(totalmedia))

bg3 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = as.numeric(min_community), y = baverage, color = kick)) +
  geom_smooth(aes(x = as.numeric(min_community), y = baverage, color = kick)) +
  xlim(0,15)

bg3 %>%
  filter(baverage > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = boardgamemechanic_cnt, y = baverage, color = kick)) +
  geom_smooth(aes(x=boardgamemechanic_cnt, y = baverage, color = kick))

bg3 %>%
  filter(baverage>0, min_community<30, yearpublished>1975) %>%
  ggplot(aes(x=yearpublished, y = (baverage), color = kick)) +
  geom_point() +
  geom_smooth()

bg3 %>%
  filter(baverage>0, min_community<30, yearpublished>1975) %>%
  ggplot(aes(x=as.numeric(languagedependence), y = baverage, color = kick)) +
  geom_point() +
  geom_smooth()

bg3 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=log(numplays), y = baverage, color = kick)) +
  geom_point(alpha=.5) +
  geom_smooth()

bg3 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=log(siteviews), y = baverage, color = kick)) +
  geom_point() +
  geom_smooth()

bg3 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=as.numeric(boardgamedesigner_cnt), y = baverage, color = kick)) +
  geom_point() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=boardgamemechanic_cnt, y = logtotalmedia)) +
  geom_point(alpha =.1) 

```



MODS
```{r}
mod1 = lm(baverage ~ totalmedia + kick, bg4)
mod2 = lm(baverage ~ logtotalmedia+kick, bg4)
mod3 = lm(baverage ~ poly(logtotalmedia,2)+kick, bg4)

sumary(mod1)
sumary(mod2)
sumary(mod3)

mod4 = lm(baverage ~ poly(logtotalmedia,2) + languagedependence +kick, bg4)
mod5 = lm(baverage ~ poly(logtotalmedia,2) + avgweight + kick, bg4)
mod6 = lm(baverage ~ poly(logtotalmedia,2) + boardgamemechanic_cnt +kick, bg4)
mod7 = lm(baverage ~ poly(logtotalmedia,2) + boardgamemechanic_cnt + kick+ I(logtotalmedia*boardgamemechanic_cnt), bg4)
mod8 = lm(baverage ~ poly(logtotalmedia,2) +avgweight+ boardgamemechanic_cnt + kick + I(logtotalmedia*boardgamemechanic_cnt), bg4)
mod9 = lm(baverage ~ poly(logtotalmedia,2) + yearpublished + kick, bg4)
mod10 = lm(baverage ~ poly(logtotalmedia,2) + I(logtotalmedia*yearpublished)+kick, bg4)
mod11 = lm(baverage ~ poly(logtotalmedia,2) + as.numeric(min_community)+kick,bg4)

oldmod7 = lm(baverage ~ poly(logtotalmedia,2) + boardgamemechanic_cnt + I(logtotalmedia*boardgamemechanic_cnt), bg4)
oldmod8 = lm(baverage ~ poly(logtotalmedia,2) +avgweight+ boardgamemechanic_cnt + I(logtotalmedia*boardgamemechanic_cnt), bg4)

sumary(mod4)
sumary(mod5)
sumary(mod6)
sumary(mod7)
sumary(mod8)
sumary(mod9)
sumary(mod10)
sumary(mod11)

MAE.func = function(vector){
  out = mean(abs(vector))
  return(out)
  }

MAE.func(mod2$residuals)  
MAE.func(mod3$residuals)
MAE.func(mod4$residuals)
MAE.func(mod5$residuals)
MAE.func(mod6$residuals)
MAE.func(mod7$residuals)
MAE.func(mod8$residuals)
MAE.func(mod9$residuals)
MAE.func(mod10$residuals)
MAE.func(mod11$residuals)

MAE.func(oldmod8$residuals)
MAE.func(oldmod7$residuals)

#choose mod 7 or 8
```

```{r}
bg4 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = baverage, y = kick))

plot(kick~baverage, bg4)

plot(baverage~kick, bg4)

bg4 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_boxplot(aes(x = baverage, y = kick))
```

Because games that started as a kick starter tend to have a much higher minimum baverage and a higher medium baverage we can assume that you'd want to include these in a model predicting baverage.

```{r}
bgkick =bg4 %>% filter(kick ==1)
bgwo =bg4 %>% filter(kick ==0)
modwithkick = lm(baverage ~ poly(log(totalmedia),2), bgkick)
modwithout = lm(baverage ~ poly(log(totalmedia),2), bgwo)
plot(baverage ~ log(totalmedia),pch=16,col=kick, bg4)
lines(sort(bgkick$logtotalmedia), 
      fitted(modwithkick)[order(bgkick$logtotalmedia)],
      col = "green",
      type = "l")
lines(sort(bgwo$logtotalmedia), 
      fitted(modwithout)[order(bgwo$logtotalmedia)],
      col = "yellow",
      type = "l")


modwithkick2 = lm(baverage ~ poly(log(numplays),2), bgkick)
modwithout2 = lm(baverage ~ poly(log(numplays),2), bgwo)
plot(baverage ~ log(numplays),pch=16,col=kick, bg4)
lines(sort(bgkick$lognumplays), 
      fitted(modwithkick2)[order(bgkick$lognumplays)],
      col = "green",
      type = "l")
lines(sort(bgwo$lognumplays), 
      fitted(modwithout2)[order(bgwo$lognumplays)],
      col = "yellow",
      type = "l")

modwkicknorm = lm(baverage ~ poly(log(totalmedia),2)+kick, bg4)
modwonorm= lm(baverage ~ poly(log(totalmedia),2), bg4)
modwkicknorm2= lm(baverage ~ poly(log(numplays),2) +kick, bg4)
modwonorm2= lm(baverage ~ poly(log(numplays),2), bg4)

anova(modwkicknorm, modwonorm)
anova(modwkicknorm2, modwonorm2)

MAE.func(modwonorm$residuals)
MAE.func(modwkicknorm$residuals)
MAE.func(modwonorm2$residuals)
MAE.func(modwkicknorm2$residuals)
```

```{r}
oldmod7AND = lm(baverage ~ poly(logtotalmedia,2) + boardgamemechanic_cnt + I(logtotalmedia*boardgamemechanic_cnt) +numplays, bg4)
oldmod8AND = lm(baverage ~ poly(logtotalmedia,2) +avgweight+ boardgamemechanic_cnt + I(logtotalmedia*boardgamemechanic_cnt)+numplays, bg4)

mod7AND = lm(baverage ~ poly(logtotalmedia,2) + boardgamemechanic_cnt + kick+ I(logtotalmedia*boardgamemechanic_cnt)+numplays, bg4)
mod8AND = lm(baverage ~ poly(logtotalmedia,2) +avgweight+ boardgamemechanic_cnt + kick + I(logtotalmedia*boardgamemechanic_cnt)+numplays, bg4)

MAE.func(oldmod7AND$residuals)
MAE.func(oldmod8AND$residuals)
MAE.func(mod7AND$residuals)
MAE.func(mod8AND$residuals)


RMSE.func = function(residuals){
  rmse = sqrt(sum((residuals)^2)/length(residuals))
  return(rmse)
}
RMSE.func(oldmod7$residuals)
RMSE.func(oldmod8$residuals)
RMSE.func(mod7$residuals)
RMSE.func(mod8$residuals)
RMSE.func(modwkicknorm2$residuals)
RMSE.func(modwonorm2$residuals)


```

```{r, eval =F}
# DONT RUN

bg4$Predict = NA

model.func=function(data){
  mod = modwkicknorm2
  return(mod)
}
for(i in 1:length(bg4$Predict)){
  data = bg4 %>% filter(!row_number() %in% c(i))
  mod = model.func(data)
  pred = bg4[i,] %>% predict(mod,.)
  bg4$Predict[i] = pred
}

RMSE.func = function(prediction, actual){
  rmse = sqrt(sum((actual-prediction)^2)/length(prediction))
  return(rmse)
}

formodkicknorm2 = RMSE.func(bg4$Predict, bg4$baverage)
```

```{r}
RMSE.func = function(prediction, actual){
  rmse = sqrt(sum((actual-prediction)^2)/length(prediction))
  return(rmse)
  }

leave.one.out.RMSE = function(dat,mod,response){
  dat$Predict = NA
  for(i in 1:length(dat$Predict)){
    data = dat %>% filter(!row_number() %in% c(i))
    pred = dat[i,] %>% predict(mod,.)
    dat$Predict[i] = pred
    }
  RMSE = RMSE.func(dat$Predict, response)
  return(RMSE)
}
```


```{r}
formod7
formod8
formod7NEW
formod8NEW
formodkicknorm2

anova(mod8, oldmod8)
```

```{r}
aamod <- lm(baverage ~ log_plays + playerage, data = player_bg_data)
summary(aamod)
player_bg_data$predict = predict(aamod, player_bg_data)

leave.one.out.RMSE(player_bg_data,aamod, player_bg_data$baverage)
MAE.func(aamod$residuals)
RMSE.func(player_bg_data$predict, player_bg_data$baverage)
```

```{r}
bg4$kickn = as.numeric(bg4$kick)
bg4 = bg4 %>% mutate(kickn=kickn-1)
rmod = lmer(baverage~1+(1|kickn),bg4,REML=T)
rmoda = lmer(baverage ~ playerage + (1|log_plays), data = player_bg_data, REML=T)
rmod1 = lmer(baverage ~ poly(logtotalmedia,2) +avgweight+ boardgamemechanic_cnt + I(logtotalmedia*boardgamemechanic_cnt) + (1|kickn), data = bg4, REML=T)
```

```{r}
bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=as.numeric(boardgamedesigner_cnt), y = kick)) +
  geom_point(alpha = .1)+
  geom_abline()

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=as.numeric(boardgamemechanic_cnt), y = kick)) +
  geom_point(alpha = .1) +
  geom_abline()

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=log(numplays), y = kick)) +
  geom_point(alpha = .1) +
  geom_abline()

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=log(numplays), y = kick)) +
  geom_point(alpha = .1) +
  geom_abline()

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=log(numplays), y = kick)) +
  geom_boxplot() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0) %>%
  ggplot(aes(x=logtotalmedia, y = kick)) +
  geom_point(alpha = .1) +
  geom_abline() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0, avgweight>0) %>%
  ggplot(aes(x=avgweight, y = kick)) +
  geom_point(alpha = .1) +
  geom_abline() 

player_bg_data%>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0, avgweight>0) %>%
  ggplot(aes(x=playerage, y = kick)) +
  geom_point(alpha = .1) +
  geom_abline() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0, avgweight>0) %>%
  ggplot(aes(x=kick, y = log_plays)) +
  geom_point(alpha = .1) +
  geom_abline() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0, avgweight>0) %>%
  ggplot(aes(x=yearpublished, y = log_plays)) +
  geom_point(alpha = .1) +
  geom_smooth() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0, avgweight>0) %>%
  ggplot(aes(x=avgweight, y = log_plays)) +
  geom_point(alpha = .1) +
  geom_smooth() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0, avgweight>0) %>%
  ggplot(aes(x=logtotalmedia, y = log_plays)) +
  geom_point(alpha = .1) +
  geom_smooth() 

bg4 %>%
  filter(baverage>0, min_community<30, yearpublished>1975, numplays>0, avgweight>0) %>%
  ggplot(aes(x=boardgamemechanic_cnt, y = log_plays)) +
  geom_point(alpha = .1) +
  geom_smooth() 
```

```{r}
gammod_numplays.totmed.avgw = bg4 %>%
  filter(baverage>0, yearpublished>1975, avgweight>0, totalmedia >0) %>%
  gam(baverage ~ s(numplays, by = logtotalmedia) + avgweight + logtotalmedia, data = ., method = "REML") 
summary(gammod_numplays.totmed.avgw)
bg4$predict = predict(gammod_numplays.totmed.avgw, bg4)
RMSE.func(bg4$predict, bg4$baverage)
gam1rmse = leave.one.out.RMSE(bg4, gammod_numplays.totmed.avgw, bg4$baverage)
gam1rmse
```

```{r}
gammod_aa <- gam(baverage ~ s(log_plays, by = as.numeric(playerage)) + as.numeric(playerage), data = player_bg_data, method = "REML")
gammod_aa.kick =gam(baverage ~ s(log_plays, by = as.numeric(playerage)) + as.numeric(playerage) +kick, data = player_bg_data, method = "REML")
gammod_ntw.kick = bg4 %>%
  filter(baverage>0, yearpublished>1975, avgweight>0, totalmedia >0) %>%
  gam(baverage ~ s(numplays, by = logtotalmedia) + avgweight + logtotalmedia +kick, data = ., method = "REML") 

gamArmse = leave.one.out.RMSE(player_bg_data, gammod_aa, player_bg_data$baverage)
gamAKickrmse = leave.one.out.RMSE(player_bg_data, gammod_aa.kick, player_bg_data$baverage)
gam2rmse = leave.one.out.RMSE(bg4, gammod_ntw.kick, bg4$baverage)

gamArmse
gamAKickrmse
gam2rmse
```

```{r}
gammod_3 =bg4 %>%
  filter(baverage>0, yearpublished>1975, avgweight>0, totalmedia >0) %>%
  gam(baverage ~ s(log_plays, by = as.numeric(playerage)) +s(logtotalmedia, by = boardgamemechanic_cnt) + as.numeric(playerage) + avgweight +boardgamemechanic_cnt, data = ., method = "REML")

gammod_4 =bg4 %>%
  filter(baverage>0, yearpublished>1975, avgweight>0, totalmedia >0) %>%
  gam(baverage ~ s(log_plays, by = as.numeric(playerage)) +s(logtotalmedia, by = boardgamemechanic_cnt) + as.numeric(playerage) + avgweight, data = ., method = "REML")

gammod_5 =bg4 %>%
  filter(baverage>0, yearpublished>1975, avgweight>0, totalmedia >0) %>%
  gam(baverage ~ s(log_plays, by = as.numeric(playerage)) +s(logtotalmedia, by = boardgamemechanic_cnt) + avgweight + kick, data = ., method = "REML")

gam3rmse = leave.one.out.RMSE(bg4, gammod_3, bg4$baverage)
gam4rmse = leave.one.out.RMSE(bg4, gammod_4, bg4$baverage)
gam5rmse = leave.one.out.RMSE(bg4, gammod_5, bg4$baverage)

gam3rmse
gam4rmse
gam5rmse
```

```{r}
gammod_6 =bg4 %>%
  filter(baverage>0, yearpublished>1975, avgweight>0, totalmedia >0) %>%
  gam(baverage ~ s(log_plays, by = logtotalmedia) + avgweight + kick, data = ., method = "REML")

gam6rmse = leave.one.out.RMSE(bg4, gammod_6, bg4$baverage)
gam6rmse

gammod_7 =bg4 %>%
  filter(baverage>0, yearpublished>1975, avgweight>0, totalmedia >0) %>%
  gam(baverage ~ s(log_plays, by = boardgamemechanic_cnt) + avgweight + kick, data = ., method = "REML")

gam7rmse = leave.one.out.RMSE(bg4, gammod_6, bg4$baverage)
gam7rmse
```



PREDICTING KICK
```{r}
bg4 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = baverage, y = kick))

logmod1 = glm(kick~baverage, family=binomial, bg4)

bg4$kickn = as.numeric(bg4$kick)
bg4 = bg4 %>% mutate(kickn=kickn-1)

plot(kickn~baverage, data=bg4, col="steelblue")
lines(sort(bg4$baverage), 
      fitted(logmod1)[order(bg4$baverage)])



```

```{r}
bg4 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = baverage, y = kick, color = weightgroup))

bg4 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = baverage, y = kick, color = ComPlayerGroup), alpha=.5)

bg4 %>%
  filter(baverage > 0, avgweight > 0, yearpublished>1975) %>%
  ggplot() +
  geom_point(aes(x = baverage, y = kick, color = log(totalmedia)), alpha=.5)
```

```{r}
logmod2 = glm(kick~baverage+log(totalmedia), family=binomial, bg4)
summary(logmod1)
summary(logmod2)

bg4$predict1 = predict(logmod1, bg4)
bg4$predict2 = predict(logmod2, bg4)

RMSE.func(bg4$predict1, bg4$kickn)
RMSE.func(bg4$predict2, bg4$kickn)
MAE.func(logmod1$residuals)
MAE.func(logmod2$residuals)
```



WORKING
```{r}
bg4 %>% 
  mutate(midplaytime = (minplaytime+maxplaytime)/2)
```
 
 
 
